AWSTemplateFormatVersion: '2010-09-09'
Description: 'Static website hosting with S3, CloudFront, Route 53, and ACM'

Parameters:
  DomainName:
    Type: String
    Description: Root domain name (e.g., example.com)
    AllowedPattern: ^[a-z0-9][a-z0-9-]{1,61}[a-z0-9]\.[a-z]{2,}$
    ConstraintDescription: Must be a valid domain name
  
  Subdomain:
    Type: String
    Description: Subdomain prefix (e.g., trading, trading-dev)
    AllowedPattern: ^[a-z0-9][a-z0-9-]{0,61}[a-z0-9]$
    ConstraintDescription: Must be a valid subdomain prefix
  
  BucketName:
    Type: String
    Description: S3 bucket name for static website hosting
    AllowedPattern: ^[a-z0-9][a-z0-9-]{1,61}[a-z0-9]$
    ConstraintDescription: Must be a valid S3 bucket name (lowercase, alphanumeric, hyphens)
  
  Environment:
    Type: String
    Description: Environment name
    AllowedValues:
      - production
      - dev
    Default: production

Resources:
  # S3 Bucket for access logs
  S3LoggingBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${BucketName}-logs'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldLogs
            Status: Enabled
            ExpirationInDays: 90
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: AccessLogging

  # S3 Bucket for static website hosting
  S3Bucket:
    Type: AWS::S3::Bucket
    DependsOn: S3LoggingBucket
    Properties:
      BucketName: !Ref BucketName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LoggingConfiguration:
        DestinationBucketName: !Ref S3LoggingBucket
        LogFilePrefix: s3-access-logs/
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: StaticWebsiteHosting

  # CloudFront Origin Access Control (OAC)
  CloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub '${Subdomain}-${Environment}-OAC'
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
        Description: !Sub 'OAC for ${Subdomain}.${DomainName}'

  # CloudFront Response Headers Policy for security
  CloudFrontResponseHeadersPolicy:
    Type: AWS::CloudFront::ResponseHeadersPolicy
    Properties:
      ResponseHeadersPolicyConfig:
        Name: !Sub '${Subdomain}-${Environment}-SecurityHeaders'
        Comment: Security headers for static website
        SecurityHeadersConfig:
          StrictTransportSecurity:
            AccessControlMaxAgeSec: 63072000
            IncludeSubdomains: true
            Override: true
          ContentTypeOptions:
            Override: true
          FrameOptions:
            FrameOption: DENY
            Override: true
          XSSProtection:
            ModeBlock: true
            Protection: true
            Override: true
          ReferrerPolicy:
            ReferrerPolicy: strict-origin-when-cross-origin
            Override: true

  # Route 53 Hosted Zone
  Route53HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Sub '${Subdomain}.${DomainName}'
      HostedZoneConfig:
        Comment: !Sub 'Hosted zone for ${Subdomain}.${DomainName}'
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # ACM Certificate
  ACMCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub '${Subdomain}.${DomainName}'
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Sub '${Subdomain}.${DomainName}'
          HostedZoneId: !Ref Route53HostedZone
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Name
          Value: !Sub '${Subdomain}.${DomainName}'

  # CloudFront Distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub 'CDN for ${Subdomain}.${DomainName}'
        DefaultRootObject: index.html
        Aliases:
          - !Sub '${Subdomain}.${DomainName}'
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt S3Bucket.RegionalDomainName
            OriginAccessControlId: !GetAtt CloudFrontOriginAccessControl.Id
            S3OriginConfig:
              OriginAccessIdentity: ''
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: true
          DefaultTTL: 86400
          MaxTTL: 31536000
          MinTTL: 0
          ResponseHeadersPolicyId: !Ref CloudFrontResponseHeadersPolicy
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 300
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 300
        ViewerCertificate:
          AcmCertificateArn: !Ref ACMCertificate
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        PriceClass: PriceClass_All
        HttpVersion: http2
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # S3 Bucket Policy - Allow only CloudFront OAC access with HTTPS enforcement
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn: CloudFrontDistribution
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          - Sid: AllowCloudFrontServicePrincipal
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: 's3:GetObject'
            Resource: !Sub '${S3Bucket.Arn}/*'
            Condition:
              StringEquals:
                'AWS:SourceArn': !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}'
          - Sid: DenyInsecureTransport
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !Sub '${S3Bucket.Arn}/*'
              - !GetAtt S3Bucket.Arn
            Condition:
              Bool:
                'aws:SecureTransport': false

  # Route 53 A Record
  Route53ARecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref Route53HostedZone
      Name: !Sub '${Subdomain}.${DomainName}'
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2  # CloudFront hosted zone ID (constant)
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        EvaluateTargetHealth: false

Outputs:
  S3BucketName:
    Description: Name of the S3 bucket
    Value: !Ref S3Bucket
    Export:
      Name: !Sub '${AWS::StackName}-S3BucketName'

  S3LoggingBucketName:
    Description: Name of the S3 logging bucket
    Value: !Ref S3LoggingBucket
    Export:
      Name: !Sub '${AWS::StackName}-S3LoggingBucketName'

  CloudFrontDistributionId:
    Description: CloudFront distribution ID
    Value: !Ref CloudFrontDistribution
    Export:
      Name: !Sub '${AWS::StackName}-CloudFrontDistributionId'

  CloudFrontDomainName:
    Description: CloudFront distribution domain name
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: !Sub '${AWS::StackName}-CloudFrontDomainName'

  CloudFrontOACId:
    Description: CloudFront Origin Access Control ID
    Value: !GetAtt CloudFrontOriginAccessControl.Id
    Export:
      Name: !Sub '${AWS::StackName}-CloudFrontOACId'

  ResponseHeadersPolicyId:
    Description: CloudFront Response Headers Policy ID
    Value: !Ref CloudFrontResponseHeadersPolicy
    Export:
      Name: !Sub '${AWS::StackName}-ResponseHeadersPolicyId'

  Route53NameServers:
    Description: Route 53 nameservers for domain registrar configuration
    Value: !Join [', ', !GetAtt Route53HostedZone.NameServers]
    Export:
      Name: !Sub '${AWS::StackName}-Route53NameServers'

  ACMCertificateArn:
    Description: ARN of the ACM certificate
    Value: !Ref ACMCertificate
    Export:
      Name: !Sub '${AWS::StackName}-ACMCertificateArn'

  WebsiteURL:
    Description: Full website URL
    Value: !Sub 'https://${Subdomain}.${DomainName}'
    Export:
      Name: !Sub '${AWS::StackName}-WebsiteURL'
