AWSTemplateFormatVersion: '2010-09-09'
Description: 'Static website hosting with S3, CloudFront, Route 53, and ACM'

Parameters:
  DomainName:
    Type: String
    Description: Root domain name (e.g., example.com)
    AllowedPattern: ^[a-z0-9][a-z0-9-]{1,61}[a-z0-9]\.[a-z]{2,}$
    ConstraintDescription: Must be a valid domain name
  
  Subdomain:
    Type: String
    Description: Subdomain prefix (e.g., trading, trading-dev)
    AllowedPattern: ^[a-z0-9][a-z0-9-]{0,61}[a-z0-9]$
    ConstraintDescription: Must be a valid subdomain prefix
  
  BucketName:
    Type: String
    Description: S3 bucket name for static website hosting
    AllowedPattern: ^[a-z0-9][a-z0-9-]{1,61}[a-z0-9]$
    ConstraintDescription: Must be a valid S3 bucket name (lowercase, alphanumeric, hyphens)
  
  Environment:
    Type: String
    Description: Environment name
    AllowedValues:
      - production
      - dev
    Default: production

Resources:
  # S3 Bucket for static website hosting
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: StaticWebsiteHosting

  # CloudFront Origin Access Identity
  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub 'OAI for ${Subdomain}.${DomainName}'

  # S3 Bucket Policy - Allow only CloudFront OAI access
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          - Sid: AllowCloudFrontOAIAccess
            Effect: Allow
            Principal:
              CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId
            Action: 's3:GetObject'
            Resource: !Sub '${S3Bucket.Arn}/*'
          - Sid: DenyAllOtherAccess
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !GetAtt S3Bucket.Arn
              - !Sub '${S3Bucket.Arn}/*'
            Condition:
              StringNotEquals:
                aws:PrincipalAccount: !Ref AWS::AccountId

  # Route 53 Hosted Zone
  Route53HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Sub '${Subdomain}.${DomainName}'
      HostedZoneConfig:
        Comment: !Sub 'Hosted zone for ${Subdomain}.${DomainName}'
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # ACM Certificate
  ACMCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub '${Subdomain}.${DomainName}'
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Sub '${Subdomain}.${DomainName}'
          HostedZoneId: !Ref Route53HostedZone
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Name
          Value: !Sub '${Subdomain}.${DomainName}'

  # CloudFront Distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn:
      - S3BucketPolicy
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub 'CDN for ${Subdomain}.${DomainName}'
        DefaultRootObject: index.html
        Aliases:
          - !Sub '${Subdomain}.${DomainName}'
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt S3Bucket.DomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}'
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: true
          DefaultTTL: 86400
          MaxTTL: 31536000
          MinTTL: 0
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 300
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 300
        ViewerCertificate:
          AcmCertificateArn: !Ref ACMCertificate
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        PriceClass: PriceClass_All
        HttpVersion: http2
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # Route 53 A Record
  Route53ARecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref Route53HostedZone
      Name: !Sub '${Subdomain}.${DomainName}'
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2  # CloudFront hosted zone ID (constant)
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        EvaluateTargetHealth: false

Outputs:
  S3BucketName:
    Description: Name of the S3 bucket
    Value: !Ref S3Bucket
    Export:
      Name: !Sub '${AWS::StackName}-S3BucketName'

  CloudFrontDistributionId:
    Description: CloudFront distribution ID
    Value: !Ref CloudFrontDistribution
    Export:
      Name: !Sub '${AWS::StackName}-CloudFrontDistributionId'

  CloudFrontDomainName:
    Description: CloudFront distribution domain name
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: !Sub '${AWS::StackName}-CloudFrontDomainName'

  Route53NameServers:
    Description: Route 53 nameservers for domain registrar configuration
    Value: !Join [', ', !GetAtt Route53HostedZone.NameServers]
    Export:
      Name: !Sub '${AWS::StackName}-Route53NameServers'

  ACMCertificateArn:
    Description: ARN of the ACM certificate
    Value: !Ref ACMCertificate
    Export:
      Name: !Sub '${AWS::StackName}-ACMCertificateArn'

  WebsiteURL:
    Description: Full website URL
    Value: !Sub 'https://${Subdomain}.${DomainName}'
    Export:
      Name: !Sub '${AWS::StackName}-WebsiteURL'
